name             'generated_cookbook'
maintainer       'Copyright Holder'
maintainer_email 'email@domain.com'
license          'Apache-2.0'
description      'Installs / configures generated_cookbook'
long_description ::File.read(File.expand_path('../README.md', __FILE__))
version          '0.1.0'
chef_version     '>= 12'
# issues_url       'https://github.com/<insert_org_here>/generated_cookbook/issues'
# source_url       'https://github.com/<insert_org_here>/generated_cookbook'
